### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by ghost** [TeXworks/texworks#842]
Dear developers,

could you provide TeXworks as a flatpak application/package? Flatpak is a new packaging format that is distribution independent and provides some modern and useful sandboxing techniques.

Regards

Jakob

**Comment by JakobJakobson** [comment]
The following files compiles the flatpak package but so far I'm not able to save or load any files. Can't really tell the reason for this. In my understanding the ```finish-args: --file-system=home``` should enable read/write access to the home directory.
Also I guess there could be room for optimization as I don't know if p7zip and wget are really needed.


```yaml
app-id: org.texworks.texworks
runtime: org.kde.Sdk
runtime-version: '5.9'
sdk: org.kde.Sdk
command: texworks
rename-appdata-file: texworks.appdata.xml
rename-desktop-file: texworks.desktop
finish-args:
  - --socket=x11
  - --share=ipc
  - --device=dri
  - --socket=wayland
  - --filesystem=home
  - --env=PATH=/usr/bin:/app/bin:/app/bin/x86_64-linux
  - --env=TEXMFCACHE=$XDG_CACHE_HOME
build-options:
  env:
    LD_LIBRARY_PATH: /app/lib:/app/lib64
modules:
- name: p7zip
  no-autogen: true
  make-args:
    - 7z
  cleanup:
    - '*'
  sources:
    - type: archive
      url: https://sourceforge.net/projects/p7zip/files/p7zip/16.02/p7zip_16.02_src_all.tar.bz2
      sha256: 5eb20ac0e2944f6cb9c2d51dd6c4518941c185347d4089ea89087ffdd6e2341f
    - type: shell
      commands:
      - sed -i 's|/usr/local|/app|g' makefile.common

- name: wget
  cleanup:
    - '*'
  sources:
    - type: archive
      url: https://ftp.gnu.org/gnu/wget/wget-1.19.tar.xz
      sha256: 0f1157bbf4daae19f3e1ddb70c6ccb2067feb834a6aa23c9d9daa7f048606384

- name: texlive
  buildsystem: simple
  sources:
    - type: file
      url: http://mirrors.ctan.org/systems/texlive/Images/texlive.iso
      sha512: 7b7f0dd0eab3bfffe52c5cd1139c7f75d029b9ff4c4ce0e57e06834705522f4ec0c02cd99a80b053c6619abda51c20a60f8e91e91781bdc2b9b60fc2e5708adb
  build-commands:
    - 7z x texlive.iso
    - chmod +x install-tl
    - "echo \"I\nn\" | TEXLIVE_INSTALL_PREFIX=/app ./install-tl -portable"
    - yes | rm -r /app/texmf-dist/doc

- name: openjpeg
  buildsystem: cmake-ninja
  sources:
    - type: archive
      url: https://github.com/uclouvain/openjpeg/archive/v2.3.0.tar.gz
      sha256: 3dc787c1bb6023ba846c2a0d9b1f6e179f1cd255172bde9eb75b01f1e6c7d71a

- name: poppler
  buildsystem: cmake-ninja
  config-opts:
    - -DCMAKE_BUILD_TYPE=release
    - -DENABLE_QT5:BOOL=true
    - -DCMAKE_INSTALL_LIBDIR:PATH=/app/lib
  sources:
    - type: archive
      url: https://poppler.freedesktop.org/poppler-0.62.0.tar.xz
      sha256: 5b9a73dfd4d6f61d165ada1e4f0abd2d420494bf9d0b1c15d0db3f7b83a729c6

- name: texworks
  buildsystem: cmake
  sources:
    - type: archive
      url: https://github.com/TeXworks/texworks/archive/release-0.6.2.tar.gz
      sha256: 22885c11d92654b0cba1f4808fc9aa3c2fdd3e5435fd89dff9aa1e67658a6339
```

The flatpak port of texstudio [texstudio flatpak port ](https://github.com/flathub/flathub/pull/381) seems very helpful at this point.

**Comment by JakobJakobson** [comment]
Actually after locally installing the package loading and saving files works as well as compiling them with pdflatex and xelatex. Lualatex however doesn't work as it says ```Unable to read environment locale: exit now.```.

**Comment by jakobjakobson18** [comment]
There has been some improvements on flatpak/flathub. On the one hand there is an "official" texlive extension [org.freedesktop.Sdk.Extension.texlive](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive) and the build manifest of [org.texstudio.TeXstudio](https://github.com/flathub/org.texstudio.TeXstudio) can be used as an inspiration for writing the manifest.

**Comment by jakobjakobson18** [comment]
The following file works on my computer.

```yaml

app-id: org.texstudio.TeXworks
runtime: org.kde.Platform
runtime-version: '5.12'
sdk: org.kde.Sdk
sdk-extension: org.freedesktop.Sdk.Extension.texlive
command: texworks
rename-appdata-file: texworks.appdata.xml
rename-desktop-file: texworks.desktop
finish-args:
#  - --socket=wayland (requires https://bugreports.qt.io/browse/QTBUG-68619 to be fixed)
  - --socket=fallback-x11
  - --share=ipc
  - --device=dri
  - --filesystem=host # lets LuaLaTeX etc. write output files, even if the document is stored outside of ~
  - --filesystem=xdg-config/kdeglobals:ro # gives application access to kdeglobals
  - --talk-name=com.canonical.AppMenu.Registrar # gives application access to dbus menu
  - --share=network # required for LanguageTool
  - --env=PATH=/usr/bin:/app/bin:/app/bin/x86_64-linux
  - --env=TEXMFCACHE=$XDG_CACHE_HOME
  - --env=LC_ALL=C # works around LuaLaTex issue with locale
  - --env=TEXINPUTS=.:~/texmf/:
build-options:
  env:
    LD_LIBRARY_PATH: /app/lib:/app/lib64
modules:
- name: texlive
  buildsystem: simple
  build-commands:
  - /usr/lib/sdk/texlive/install.sh

- name: openjpeg # build dependency of poppler
  buildsystem: cmake-ninja
  sources:
    - type: archive
      url: https://github.com/uclouvain/openjpeg/archive/v2.3.0.tar.gz
      sha256: 3dc787c1bb6023ba846c2a0d9b1f6e179f1cd255172bde9eb75b01f1e6c7d71a

- name: poppler # build dependency of TeXstudio
  buildsystem: cmake-ninja
  config-opts:
    - -DCMAKE_BUILD_TYPE=release
    - -DENABLE_QT5:BOOL=true
    - -DCMAKE_INSTALL_LIBDIR:PATH=/app/lib
  sources:
    - type: archive
      url: https://poppler.freedesktop.org/poppler-0.71.0.tar.xz
      sha256: badbecd2dddf63352fd85ec08a9c2ed122fdadacf2a34fcb4cc227c4d01f2cf9

- name: texworks
  buildsystem: cmake
  build-commands:
    - install -Dm644 res/images/TeXworks-128.png /app/share/icons/hicolor/128x128/apps/org.texworks.TeXworks.png
    - install -Dm644 res/images/TeXworks.png /app/share/icons/hicolor/512x512/apps/org.texworks.TeXworks.png
  cleanup-platform:
    - /bin
    - /mkspecs
  sources:
    - type: archive
      url: https://github.com/TeXworks/texworks/archive/release-0.6.3.tar.gz
      sha256: b4695539b9666935d2c467cc618c7d79c174e2ec728e31f72df8534862a5c290

```
